service: proyecto-final-restaurante

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-2
  apiGateway:
    shouldStartNameWithService: true 

# Se declaran las funciones
functions:
  hacerPedido:
    handler: handler.hacerPedido
    events: 
      - http:
          method: POST
          path: /hacerPedido

    iamRoleStatements:
      - Effect: Allow
        Action:
          - s3:PutObject
          - s3:GetObject
        Resource: 
          - arn:aws:s3:::order-backup-bucket-proyecto-final-kevindavid
      - Effect: Allow
        Action:
          - sqs:SendMessage
        Resource: 
          - arn:aws:sqs:us-east-2:667168568942:order-queue
      - Effect: Allow
        Action:
          - ses:SendEmail
          - ses:SendRawEmail
        Resource: "*"

  obtenerPedido: 
    handler: handler.obtenerPedido
    events: 
      - http:
          method: GET
          path: /obtenerPedido

# Se crea el Bucket
resources:
  Resources:
    Bucketkevindavid:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: order-backup-bucket-proyecto-final-kevindavid
        LifecycleConfiguration:
          Rules:
            - Id: DeleteAfterTwoDays
              Status: Enabled
              ExpirationInDays: 2

    # Se crea la base de datos MySQL
    Databasekevindavid:
      Type: AWS::RDS::DBInstance
      Properties:
        DBName: restaurantebd
        AllocatedStorage: 20
        DBInstanceClass: db.t2.micro
        Engine: MySQL
        EngineVersion: 5.7
        MasterUsername: admin
        MasterUserPassword: admin123
        MultiAZ: false
        StorageType: gp2
        PubliclyAccessible: true
        VPCSecurityGroups:
          - sg-086e3bf49532abbf5

    # Se crea grupo de seguridad con sus reglas
    RDSSecurityGroupIngress:
      Type: AWS::EC2::SecurityGroupIngress
      Properties:
        GroupId: sg-086e3bf49532abbf5
        IpProtocol: tcp
        FromPort: 3306
        ToPort: 3306
        CidrIp: 0.0.0.0/0

    # Se crea la cola
    Queuekevindavid:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: order-queue
        DelaySeconds: 15
        MessageRetentionPeriod: 1209600
